services:
  frontend:
    build:
      context: ./frontend
      args:
        - BACKEND_URL=${BACKEND_URL}
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - 3000:3000
    environment:
      - BACKEND_URL=${BACKEND_URL}

  backend:
    build: ./backend
    expose:
      - 3001
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3001 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 2m
